### ISSUE TITLE
Visionmode EH issue with drone, selecting night vision.

### ISSUE THREAD

**Issue by Tommo-S** [CBATeam/CBA_A3#1004]
**Arma 3 Version:** `1.84` stable
**CBA Version:** `3.8.0` stable

**Mods:**
```
- CBA_A3
```

**Description:**
- Visionmode player event handler doesn't fire when switching to nightvision while controlling a drone. 

**Steps to reproduce:**
- Add Visionmode player event handler. Remote control a drone. Switch vision modes. It reports when changing from night vision to thermal, thermal to thermal, and thermal to normal vision, but night vision is never reported.
Example of the eventhandler code.
["visionMode", {systemChat str _this}, false] call CBA_fnc_addPlayerEventHandler;

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- [pastebin](https://pastebin.com/watx2egd))

**Comment by commy2** [comment]
>thermal to thermal

Is this referring to the transition "White Hot to Black Hot"? Because that is the change I expected not to trigger the event instead of "Normal -> NVG".

**Comment by Tommo-S** [comment]
No, it's referring to normal -> NVG.

White Hot -> Black Hot fires for drones.

**Comment by commy2** [comment]
By "this", I meant the part where you said "thermal to thermal". I know that this PR is about "normal to nvg", but it is equally puzzling to me that the event triggers for one thermal mode to another.

**Comment by Tommo-S** [comment]
Sorry, yes, that was referring to "thermal to thermal".

**Comment by commy2** [comment]
Strange indeed. Which drone did you try this on? Just so I can repro when I'm back at my desktop pc in roughly 9 hours.

**Comment by Tommo-S** [comment]
The darter and the jets DLC UAV, I've forgotten it's name.

**Comment by commy2** [comment]
The player event handler framework is based on `CBA_fnc_currentUnit`. That function reports the current avatar, which is not the same as `player` while remote controlling an AI via Zeus. The function does however not report the UAV entity inside the UAV vehicle as "currentUnit" when controlling a drone.
For some reason, while controlling a UAV and while in night vision mode:
```sqf
currentVisionMode player // 0
currentVisionMode driver cameraOn // 1
```
while in thermal mode:
```sqf
currentVisionMode player // 2
currentVisionMode driver cameraOn // 2
```
and in normal mode:
```sqf
currentVisionMode player // 0
currentVisionMode driver cameraOn // 0
```

I think it would make sense if CBA_fnc_currentUnit reported the UAV entity instead of the player when controlling a UAV. That is the equivalent to Zeus remote control, but apparently not picked up by reading the `bis_fnc_moduleRemoteControl_unit` variable.
Not exactly sure on how to fix this. `getConnectedUAV` reports the UAV vehicle, which is not what we want (we want the UAV entity instead, i.e. the driver or gunner of the UAV vehicle).
Changing this core function could break stuff in ACE, but honestly it more likely fixes things :P

**Comment by commy2** [comment]
Debug script:
```sqf
"CBA_Debug" cutRsc ["RscTitleDisplayEmpty", "PLAIN", 0, true];
private _display = uiNamespace getVariable "RscTitleDisplayEmpty";

private _vignette = _display displayCtrl 1202; 
_vignette ctrlShow false; 

private _control = _display ctrlCreate ["RscText", -1];

private _width = safezoneH/5;
private _height = _width/5 * (safezoneW/safezoneH);;
private _left = 0.5 - _width/2;
private _top = 0.5 - _height/2;

_control ctrlSetPosition [_left, _top, _width, _height];
_control ctrlCommit 0;

commy_visionMode = [_control];

["visionMode", {
    params ["_unit", "_mode"];
    (commy_visionMode#0) ctrlSetText str _mode;
}, false] call CBA_fnc_addPlayerEventHandler;
```
