### ISSUE TITLE
Asking for Arma 3 monetization

### ISSUE THREAD

**Issue by ehylla93** [CBATeam/CBA_A3#1109]
Hello,

because I didn't find any email for other contact possibilities I would ask for a permission to use this mod to get the permission for a monetization server.

I would like to be contacted to eric@hylla-erfurt.de to give you further information.

Regards

**Comment by commy2** [comment]
Disclaimer: This is how I see things personally, I don't speak for anyone else involved in the project or as some kind of project manager or anything.

CBA is free software licensed under GPL v2. The FAQ of the authors of the license says that you are [allowed to sell copies of the program for money](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#DoesTheGPLAllowMoney), which seems to me to be the applicable rule here.

The FAQ of the BI monetization rule however states:

>On my server I am using mods created by other people. May I get approval to monetize?

>You may, but ONLY if you have proper permission from ___all of the authors___ of such mods. Monetizing without it contravenes our licenses.

It seems impossible to me to get permission from every author, because this mod is 10 years old according to the git history alone and some authors haven't been around for years.
