### ISSUE TITLE
Zeus cannot edit supply crates

### ISSUE THREAD

**Issue by FlaShG** [CBATeam/CBA_A3#1139]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.1` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
Zeus (both virtual and not) cannot edit contents of supply crates, neither pre-existing ones nor self-placed. The crate content editing window displays none of the items in the crate, and none of the edits done by Zeus are actually applied when clicking OK.

**Steps to reproduce:**
- Launch Arma with only CBA.
- Start any Zeus scenario.
- Place any supply crate.
- Edit the crate. It is displayed as empty.
- Add anything to the crate and confirm.
- Edit the crate again. It's displayed as empty again.
- Open the crate with a player entity. All of the crate's original items are there, but none of the items added by Zeus.

**Where did the issue occur?**
- Self-Hosted Multiplayer, Editor (Multiplayer)

**RPT log file:**
- [gist](https://gist.github.com/FlaShG/73add6a9a1ad94df735ed94cddc3c75c)

**Comment by commy2** [comment]
```
[CBA] (ui) Test OK: (cba_ui_fnc_preload3DEN is defined) x\cba\addons\ui\test_preload.sqf:7
[CBA] (ui) Test OK: (cba_ui_fnc_preloadCurator is defined) x\cba\addons\ui\test_preload.sqf:20
[CBA] (ui) ERROR: Test FAIL x\cba\addons\ui\test_preload.sqf:43
            (_vanilla isEqualTo _cba) cba_ui_fnc_preloadCurator
```
(preload3DEN check fails silently, because _vanilla undefined)

Diffs 1.90-1.92
3den: https://gist.github.com/commy2/613f277068e2240a6dd7394bde410364/revisions
curator: https://gist.github.com/commy2/0287b986d3543916bfbd1d4c67e25513/revisions

relevant curator:
```sqf
-                            _addonListType pushback [_weapon,_displayName,_displayNameShort,_picture,_type,false];

+                            _addonListType pushback [_displayName,_displayNameShort,_weapon,_picture,_type,false];
```
etc.

Fuckers made setting AmmoBox_list in 3den a scheduled script, so the test will have to be written scheduled too (longer load times :S). Test only.

- [ ] add magwell stuff

**Comment by commy2** [comment]
@FlaShG 
Is this resolved in 3.11.2?
[BIF poster](https://forums.bohemia.net/forums/topic/168277-cba-community-base-addons-arma-3/?page=51&tab=comments#comment-3356746) claims otherwise.

**Comment by FlaShG** [comment]
The update checks out for us in the following tests:
* Unit with GM Module (custom scenario)
  * With a pre-existing crate
  * With a crate placed by GM
* Virtual GM (default scenario)
  * With a crate placed by GM

In all cases, the GM sees the same inventory as the players, and the crate can be edited (including clear). We tested only with a completely unconstrained GM.

**Comment by FlaShG** [comment]
@commy2 We found the issue - [Achilles](https://steamcommunity.com/sharedfiles/filedetails/?id=723217262) replaces the standard UI for crate editing, and when using this mod, the bug happens with the new CBA patch. I assume that Achilles depends on CBA working as it did before. I also assume that it's the Achilles' maintainer's job to fix the issue from here on.

**Comment by commy2** [comment]
Thanks for finding this. That's unfortunate.

The arsenal data is essentially a big array containing sub-arrays for all available items. All CBA does is to precompile this array in a more effective way and cache it, which tremendously speeds up load times. CBA does not changes the UI which interprets this data.

In 1.92 BI changed the order of the sub-arrays. They switched the positions of the displayed name (i.e. `MX 6.5 mm`) and the classname (i.e. `arifle_MX_F`), presumably to enable alphabetical sorting easily.

Therefore after 1.92 and when using CBA the list would be empty, because `MX 6.5 mm` is not a valid classname. (If there were a weapon with displayed name equal to the classname it would still be shown).

Achilles replaces the UI part of Zeus. Therefore when using Achilles and old CBA, you would still be seeing all items, because both UI and item array creating remain unaffected by the switch by BI as they were both overwritten with scripts using the old order of classname and displayed name.

Now after the CBA update, CBA is using the 1.92 new order. Therefore when using Achilles which is still based on the old order, the same issue of `MX 6.5 mm` not being a valid classname happens, just in the opposite position of the sub-array.

CBA has to comply with the change of BI, otherwise when using only CBA the list would be empty. Achilles must switch to the new order too. In the mean time, you can use the old version of CBA (3.11.1) when using Achilles and the new version of CBA (3.11.2) when not using Achilles.
