### ISSUE TITLE
magazines not attached to weapons in use are omitted from CBA_fnc_uniqueUnitItems

### ISSUE THREAD

**Issue by zharf** [CBATeam/CBA_A3#1156]
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2` (stable)

**Mods:**
```
- CBA_A3
```

**Description:**
- `CBA_fnc_uniqueUnitItems` does not return any magazines not currently attached to a weapon in use by the unit. It seems that `getItemCargo` doesn't return them while `magazines` does.

**Steps to reproduce:**
- Place down ammo carrier, drop weapons and observe result of `CBA_fnc_uniqueUnitItems`

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- https://gist.github.com/zharf/208e4ab33df63c9f0283a0e8264d1df2

**Comment by commy2** [comment]
I pinged dedmen, because from looking at the code, it seems that uniqueUnitItems is not supposed to return any magazine, and the command returning loaded magazines at all (if _weaponItems flag is set to true) is just a byproduct of optimization: this function also reports the empty string as item (no attachment at atleast one hardpoint), even though it is not an item, because the function is used for writing optimized code. (Substitude for a missing command like `_unit hasItem "class"`).

**Comment by dedmen** [comment]
>it seems that uniqueUnitItems is not supposed to return any magazine
True, it was not written for that. It was written as a fast way to check if the player has "items" in their inventory, magazines are not items.
But I see that from a API standpoint it makes much more sense to include that.
