### ISSUE TITLE
Scripted Optics breaks ACE Kestrel + DUI Squad Radar

### ISSUE THREAD

**Issue by Blutze** [CBATeam/CBA_A3#1193]
**Arma 3 Version:** `1.94.145903` (stable)
**CBA Version:** `3.12.0` (stable)

**Mods:**
```
- CBA_A3
- ACE3 3.12.6
- DUI Squad Radar 1.5.4 or 1.5.5
- BWMod 2.1.2 or RKSL Attachments 3.01+ (or probably any other mod using Scripted Optics)
```

**Description:**
The ACE PDAs have the option to be shown in a corner for long-term display instead of in the center for inputs & interaction. Putting the Kestrel into that mode makes both the Kestrel and the Squad Radar flicker, disappearing and redrawing about once per second.

DUI has a setting to refresh the compass bearing only every few seconds. Setting that to an extreme timer and turning around with the Kestrel up shows the bearing update on every flicker-based redraw.

As long as the flickering is active, there are RPT errors: `11:53:53 Wrong color format`, appearing once a second.

**Steps to reproduce:**
- Obtain ACE Kestrel
- Make sure Squad radar isn't disabled (there are settings to hide it when not in a group etc)
- Put Kestrel into show-in-the-corner mode
- Behold: It flickers.

**Where did the issue occur?**
- Singleplayer

**RPT log file:**
- https://gist.github.com/Blutze/48014929cbccd3102fea632e981a3cd2

**Video:**
- https://www.twitch.tv/videos/459937836

**Comment by bux** [comment]
Does this happen with only CBA and ACE3?

**Comment by commy2** [comment]
Kestrel:
https://github.com/acemod/ACE3/blob/master/addons/kestrel4500/functions/fnc_displayKestrel.sqf#L67

Kestrel uses hard coded layer. This layer may be taken by any other cutX use. Very likely here, because layer 3 was chosen, so the third layer assigned by the proper named layer syntax will hide the Kestrel and vice versa. Scripted optics take one for the pause menu, so it may push DUI to take 3, which makes DUI and Kestrel end up in an infinite update loop.

Need to change this 3 in ACE to QGVAR(CutLayer) or some other name. The 3 appears in multiple places in ACE Kestrel.

**Comment by commy2** [comment]
ref https://github.com/acemod/ACE3/pull/7279
