### ISSUE TITLE
Joint Muzzle for 7.62x54R and/or SVD rifle

### ISSUE THREAD

**Issue by 10Dozen** [CBATeam/CBA_A3#1226]
Some russian weapon like SVD and PKM (both chambered with 7.62x54R caliber) can be equipped with muzzle devices (suppressors/flash hiders), but there is no specific joint muzzle class for these items.

**Solution you'd like:**
As SVD has a bit specific mounting for muzzle devices - it will be good to have two separate muzzle mounts: one for SVD (asdg_MuzzleSlot_762x54_SVD) and one common 7.62x54R (asdg_MuzzleSlot_762x54)

**Alternatives you've considered:**
At least single asdg_MuzzleSlot_762x54 joint muzzle class

**Comment by Blutze** [comment]
Wouldn't the "common" 7.62x54R mount be the `asdg_MuzzleSlot_762R` we already have?

**Comment by 10Dozen** [comment]
Then why there is asdg_MuzzleSlot_762MG and R when there is asdg_MuzzleSlot_762 already? I don't understand what logic do you use in this case - bullet diameter is quite the same for all 7.62x(anything) ammo.

**Comment by Blutze** [comment]
> Then why there is asdg_MuzzleSlot_762MG and R when there is asdg_MuzzleSlot_762 already?

Bites me. Thats been there since long before I purchased the game.

Sounds like they should both get special JR slots. I'm not sure what to do with that vanilla bullpup Dragunov though - it can take regular 7.62 suppressors (don't try this at home, there is a 0.1 mm difference in bullet diameter) even without any mods, and they are mounted over the flash hider like on most western guns.
