### ISSUE TITLE
Question: CBA Settings via paramsArray

### ISSUE THREAD

**Issue by LAxemann** [CBATeam/CBA_A3#1256]
Heya,

all links forward to gitHub, so pardon me if this is not the right place and way to ask.

I'd like to use the mission's parameters/paramsArray (https://community.bistudio.com/wiki/Arma_3_Mission_Parameters) to dynamically set some CBA settings.

My plan was to use the paramsArray to set #defines and then use #ifdef in the cba_settings.sqf of the mission. Looking through the code of the CBA_Settings system, it appears as if most settings are already loaded pre-Init. The paramsArray, however, is only available for clients somewhen after preInit, but before postInit. 

From my understanding, overwriting the respective settings variables post-init will generally work, but may cause issues with settings that require a restart of the mission. Is that correct?

**Comment by commy2** [comment]
Yes.

**Comment by LAxemann** [comment]
> 
> 
> Yes.

merci beaucoup!

**Comment by LAxemann** [comment]
Alright, I have to reopen the question.
Is there a possibility/chance to change CBA Settings (also those that can't be changed Mid-Session) via the loby parameters/paramsArray?
If not, is there a chance such a functionality could be included in a future update?

**Comment by commy2** [comment]
>also those that can't be changed Mid-Session

No, because the briefing is already mid session.

The others can be changed by the ADDON OPTIONS button in the briefing. On your own risk, you can use [CBA_settings_fnc_set](https://github.com/CBATeam/CBA_A3/blob/master/addons/settings/fnc_set.sqf) to set the value of a setting on the local machine. Technically all settings can be changed, but the ones marked as having no effect when changed mid mission, likely have no effect when changed mission, because they were specified as such by the author.

**Comment by LAxemann** [comment]
Huh, bummer, but I understand. Thanks for the swift reply!
