### ISSUE TITLE
off by one error in CBA_fnc_mapGridToPos

### ISSUE THREAD

**Issue by warzen** [CBATeam/CBA_A3#1362]
**Mods (complete and add to the following information):**
- **Arma 3:** 1.98.146373
- **CBA:** `3.15.1
_Make sure to reproduce the issue with only CBA on a newly created mission!_
Only CBA, new mission.

**Description:**
both coordinates returned by CBA_fnc_mapGridToPos are wrong by one unit

**Steps to reproduce:**
example1: "000000" call CBA_fnc_mapGridToPos => [-1,-1,0] , it should be [0,0,0]
example2: "141212" CBA_fnc_mapGridToPos => [14099,21199,0] and that's in 140,211, not in 141,212

**Where did the issue occur?**
Editor (Singleplayer)

**Comment by Drofseh** [comment]
~~Hmm, strictly speak a grid designation refers to the whole square as well, not the bottom left corner.~~
~~Grid 141212 encompasses everything from positions [14100.00,21200.00] to [14199.99,21299.99] inclusive.~~
~~So in a mapping/military context it might make sense to return the centre of the grid for position.~~
~~`"141212" call CBA_fnc_mapGridToPos //return [14150,21250]`~~

Apparently it's supposed to be returning either centre or upper left if the `_doOffSet` parameter is true or false.
Upper left is *always* wrong in a map context since the grid number is taken from the bottom left of the grid square.

**Comment by warzen** [comment]
["0000000000",true] call CBA_fnc_mapGridToPos is returning [-1,-1,0] so in fact we have two bugs here:
- the off by one error on the calculation
- the fact that the lower left is return when _doOffSet is false. In this case, the two bugs are occuring.
