### ISSUE TITLE
Remove listed files or install additional accepted keys.

### ISSUE THREAD

**Issue by VergariusKane** [CBATeam/CBA_A3#310]
please fix Remove listed files or install additional accepted keys.
cba_class_eventhandlers.pbo
cba_extended_eventhandlers.pbo
cba_xeh_a3.pbo

i have to delete this files every single time i want to play Desolation mod... its turning annoying

**Comment by commy2** [comment]
That's a Steam thing iirc. Nothing we can do. I think you have to delete these files from another folder on your hd.

Or just don't use Steam.

**Comment by commy2** [comment]
Here is that folders default location: `C:\Program Files (x86)\Steam\steamapps\workshop\content\107410`

Make sure you don't have the game running while browsing the Workshop. Your OS won't have write access to these files otherwise.

If you still have questions about this feature, please contact Steam Support or Bohemia instead.

**Comment by VergariusKane** [comment]
Thx a lot.
