### ISSUE TITLE
Why is XEH Disabled on Thing class inheritance

### ISSUE THREAD

**Issue by GuzzenVonLidl** [CBATeam/CBA_A3#565]
Out of curiosity, Is there a specific reason why XEH is disabled by default on both Static and Thing? or is it just as simple as a performance thing?

https://github.com/CBATeam/CBA_A3/blob/master/addons/xeh/CfgVehicles.hpp#L24

**Comment by commy2** [comment]
Was originally made for performance concerns in A2. Many objects inheriting from that are map objects.
Since then XEH has been improved a lot though, so maybe we could reenable it for this and everything else.
HOWEVER, just deleting `XEH_DISABLED;` won't achive much. Many classes inheriting from `ThingX: Thing` redefine `class EventHandlers` without inheriting the original one from `All` or `Thing`. All these object classes would then print an RPT about not being supported natively and they would trigger the fallback loop (so it would still "work").
I could live with that if it were only for vanilla classes. One evening going through all of them and I would've added the CBA_ExtendedEventHandlers` class as sub class to all of them.
But then there is 3rd party addons... "Why does CBA spam my RPT all of the sudden, the update broke it!". I don't really want to deal with that. Especially since there are paranoid people that don't understand how these things work and that spamming 50-100 lines at mission start does not slow down the game (because only printing errors __during__ the mission would affect performance by writing to the RPT). 
As you can see, lot's of :salt: on my side.
