### ISSUE TITLE
CBA_fnc_getPos returning array reference instead of an array-copy

### ISSUE THREAD

**Issue by highhead** [CBATeam/CBA_A3#584]
CBA_fnc_getPos is returning the feeded array reference instead of an array-copy, 
which f.e. then bugs out CBA_fnc_RandPos which will alter the originally passed position instead of only returning a new one. The latter related to this commit, where the array-copy has been removed:

https://github.com/CBATeam/CBA_A3/commit/8a4d6c21d8fd700c0337dcf964bf087ba36a9fdc#diff-bee87607846a78814c6fe5729a46a521L24 - line 24

In our case (ALiVE), the usage of the function also causes positions beeing altered in our hashes data.

**Comment by PabstMirror** [comment]
I think getPos returning an input reference is ok and we just need to fix randPos

**Comment by marceldev89** [comment]
IMO, the fix should be done in fnc_getPos. It makes no sense for `_somePos call CBA_fnc_getPos;` to return a reference.

**Comment by commy2** [comment]
@highhead @marceldev89 
`CBA_fnc_getPos` and `CBA_fnc_randPos` are very old functions and their age is showing with them. The first one has problems with being inconsistent in that it reports AGL under some and AGLS under different conditions. There is no real way to tell which is the expected behavior and this cannot be fixed if we want to keep backwards compatibility.
`CBA_fnc_randPos` is a function that isn't really needed anymore in A3. Instead you should use the alternative syntax of `getPos`:
```sqf
_position getPos [random _radius, random 360]
```
https://community.bistudio.com/wiki/getPos#Alternative_Syntax

**Comment by commy2** [comment]
>To get a uniform distribution:
>_position getPos [_radius * sqrt (random 1), random 360]
