### ISSUE TITLE
CBA_fnc_globalExecute does not work

### ISSUE THREAD

**Issue by dixon13** [CBATeam/CBA_A3#713]
**Arma 3 Version:** `1.72` stable
**CBA Version:** `3.4.0.170627` stable

**Mods:**
```
- CBA_A3,
- ACE3
- ACEX
- ALiVE
- RHSUSAF
- ASR AI
- TFAR
- JSRS
```

**Description:**
- Function does not execute as intended.
- Execute the below code and what is printed to RPT after executing this function is down below.

**Steps to reproduce:**
- Execute global execute with any kind of code
- Try this code...
```
[-1, { 
 params["_name", "_side"]; 
 [_side, "HQ"] sideChat format["%1 is awesome!!!", _name]; 
},["MyName", west]] call CBA_fnc_globalExecute;
```

**Where did the issue occur?**
- Dedicated

**RPT log file:**
```
22:54:53 Client: Network message 131633 (update info 8ca9efa0) is pending
```

**Comment by dixon13** [comment]
I know this function is deprecated but noticed it in one of my scripts I haven't updated in a very long time. I will be utilizing a different way of handling this but this is pretty much to let others know as well that this function is broken atm.

**Comment by PabstMirror** [comment]
CBA_fnc_globalExecute uses the `remoteExec` command which can be blocked
See: https://community.bistudio.com/wiki/Arma_3_Remote_Execution#Security

You could test this if the following code works:
```
["test 1234", {systemChat _this}] remoteExec ["BIS_fnc_call", 0];
```

**Comment by commy2** [comment]
Can anyone confirm that it doesn't work?

**Comment by dixon13** [comment]
I tested the same code in the example above I posted with `remoteExec` on my dedicated box and it worked.

**Comment by dixon13** [comment]
Just tested it again on dedicated server and it works.
```SQF
_msg = "MyName"; 
[[west, "HQ"], format["%1 is awesome!!!", _msg]] remoteExec ["sideChat", west];
```

**Comment by dixon13** [comment]
@PabstMirror I have Remote Execution security set as default so anything should execute.

**Comment by commy2** [comment]
You tried the wrong thing. You need to make sure `BIS_fnc_call` is white listed.

So for example:
```sqf
["MyName", {
    systemChat str _this;
}] remoteExec ["BIS_fnc_call"];
```

**Comment by dixon13** [comment]
Ok so I tried this...
```SQF
[[west, "dixon13"], { 
    params ["_side", "_name"];
    [_side, "HQ"] sideChat format["%1 is awesome!!!", _name];
}] remoteExec ["BIS_fnc_call"];
```
It didn't work.

I guess [wiki](https://community.bistudio.com/wiki/CfgRemoteExec) is confusing to me as I thought not defining `CfgRemoteExec` would mean allowed everything to be remotely executed.

**Comment by commy2** [comment]
You can take a look at how `CBA_fnc_globalExecute` works here:
https://github.com/CBATeam/CBA_A3/blob/master/addons/network/fnc_globalExecute.sqf#L27-L52

As you can see, it is just a wrapper for `remoteExec "BIS_fnc_call"` at this point. That is also the sole reason it is deprecated: there is no reason to use it as it provides no benefits at the cost of unnecessary computation time that could be avoided. There are no intentions to remove the function in the near future however.
The function was changed to use the `remoteExec` framework so that it cannot be abused by cheaters to execute arbitrary code. That would be bad as it would mean that using CBA would provide additional potential "security" risks, which is not acceptable.

**Comment by dixon13** [comment]
for anyone that stumbles to this. Whitelist `BIS_fnc_call` in [CfgRemoteExec](https://community.bistudio.com/wiki/Description.ext#CfgRemoteExec). Closing for now.
