### ISSUE TITLE
Ability to bind to Joysticks

### ISSUE THREAD

**Issue by benringrose** [CBATeam/CBA_A3#825]
Is there a possibility that we are able to bind different controls to buttons/switches on a HOTAS (for me its the Thrustmaster Warthog), this is mainly for custom eject scripts that we are using along with the ability to bind TFAR Radio controls to it.

Not sure if the Arma 3 framework would allow this to work, or if it has been implemented and I am just having a Dumb Dumb moment (or a couple of dozen)

**Comment by commy2** [comment]
You can't bind addon actions to joystick keys, because the Arma API (for addons and scripters) does not allow for it. You can however use a third party tool like [JoyToKey](https://joytokey.net/en/) and bind your joystick to a proxy keyboard key and bind the action to that key instead.
"Is there a possibility" to add this feature in the future? There kind of is, but it would require leaving the Arma / SQF API behind and write a e.g. [DirectX](https://msdn.microsoft.com/en-us/library/windows/desktop/dn643741(v=vs.85).aspx) DLL extension for the game.
This is however beyond my salary.

Related to #789. Could close this and amend the other backlog issue.

**Comment by dedmen** [comment]
The DirectX extension is ready since last week https://github.com/dedmen/intercept_cba

**Comment by commy2** [comment]
^ This wouldn't require a dll, but it may be not as neat.
