### ISSUE TITLE
CBA Keybinding: delete key doesn't execute code when the ingame map is open

### ISSUE THREAD

**Issue by Timi007** [CBATeam/CBA_A3#880]
**Arma 3 Version:** `1.80.143869`
**CBA Version:** `3.6.1.180131`

**Mods:**
```
- CBA_A3
```

**Description:**
- Normally keys assined with the CBA keybinding function will execute the given code even if the ingame map is open. However, if the delete key (DIK Code: 0xD3 or 211) is assigned (with or without modifiers), the code will not be executed when the ingame map is open, only if it's closed.

**Steps to reproduce:**
- open editor
- create a scenario
- create a player (with map)
- create an init.sqf and put the following in it:
```
n = 0;
["Adding Mod","add_one_key","Add 1", 
   {
        n = n + 1;
        systemchat (str n);
    }, 
    "", 
    [0xD3, [false, false, false]]
] call CBA_fnc_addKeybind;
```
- play the scenario in singleplayer/multiplayer
- press the delete key: the ingame chat should show you a number (if the key is pressed again, the number should count 1 up)
- open the ingame map
- press the delete key: nothing happens/the number stays the same

**Where did the issue occur?**
- Editor (Singleplayer) / Editor (Multiplayer)

**RPT log file:**
- N/A

**Comment by PabstMirror** [comment]
```
(findDisplay 12) displayAddEventHandler ["KeyDown", { systemChat format ["12: %1", _this]}]; 
(findDisplay 46) displayAddEventHandler ["KeyDown", { systemChat format ["46: %1", _this]}];
```
In normal 3d, only 46 fires.
On the map you get odd results, where both 12 and 46 will fire for most keys,
but a few key only fire on 12, mainly Delete (but not insert), Tab, Page Up/Down, arrow keys, Numpad keys (except 0 and 5???)

And if you have the command menu up, then all keys are detected on both.

Right now we add the keyDown handles to the main display (46)
Maybe we could add keyDown handler to both, and if map is open ignore 46, otherwise ignore 12?

**Comment by commy2** [comment]
Will look into this and maybe add a backup handler to display 12 / map display handling the blocked keys.
