### ISSUE TITLE
Can't get an Array of "compatibleItems"

### ISSUE THREAD

**Issue by stafmoony** [CBATeam/CBA_A3#969]
**Arma 3 Version:** `1.84` (stable / rc / dev)
**CBA Version:** `3.8.0.180801` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
```

**Description:**
I try to write a script that adds all attachments for each weapons in an Array to an ACE Arsenal. 
I think I have a somewhat working idea:

```
_attachmentsOptics = {
    getArray (configfile >> "CfgWeapons" >> _x >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems");
} forEach _weapons;

_attachmentsMuzzle = {
    getArray (configfile >> "CfgWeapons" >> _x >> "WeaponSlotsInfo" >> "MuzzleSlot" >> "compatibleItems");
} forEach _weapons;

_attachmentsPointer = {
    getArray (configfile >> "CfgWeapons" >> _x >> "WeaponSlotsInfo" >> "PointerSlot" >> "compatibleItems");
} forEach _weapons;

_attachmentsUnderbarrel = {
    getArray (configfile >> "CfgWeapons" >> _x >> "WeaponSlotsInfo" >> "UnderBarrelSlot" >> "compatibleItems");
} forEach _weapons;

_attachments = _attachmentsOptics + _attachmentsMuzzle + _attachmentsPointer + _attachmentsUnderbarrel;
```
Where _weapons is the Array with the weapon classes and _attachments is later added to the Arsenal.

However, my problem now is that `Getarray (configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems")` (This is the code I'm using to debug ingame) is not working. 
In theory it would give me an Array of all optics for the weapon I'm holding but in my tests it only gives me an empty array. 

Why do I ask here? I'm pretty sure that CBA is causing my trouble here.

When I use `Getarray (configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems")` in Vanilla I get my Array of Optics. 
When I use it in a game with only CBA loaded I get the Empty Array. 

I dunno if it is of use but, when I just use `configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems"` I get "bin\config.bin/asdg_OpticRail1913/compatibleItems" 

**Steps to reproduce:**
- Launch the game with CBA loaded
- Go in the Editor
- Place a Unit with Primary Weapon
- Test the Mission
- Use: `Getarray (configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems")` in the Debug console.
- Use: `configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems"`

**Where did the issue occur?**
- Editor (Singleplayer)

**RPT log file:**
https://pastebin.com/Lwc6qQb0

**Comment by PabstMirror** [comment]
`compatibleItems` can be an array or a **class** with sub entries (with x=1, indicating compatibility)

e.g.
```
    class compatibleItems {
        optic_Nightstalker = 1;
        optic_tws = 1;
        optic_tws_mg = 1;
```

Check out https://github.com/CBATeam/CBA_A3/blob/master/addons/jr/fnc_compatibleItems.sqf
An example that's similar to your existing code:
```
private _returnValue = [];       
private _cfgCompatibleItems = configfile >> "CfgWeapons" >> (primaryWeapon player) >> "WeaponSlotsInfo" >> "CowsSlot" >> "compatibleItems";
if (isArray _cfgCompatibleItems) then {  // original way, it's an array, just return it
    _returnValue = getArray _cfgCompatibleItems;
} else {
    if (isClass _cfgCompatibleItems) then { // alt way, it's a class, get sub entries
        _returnValue = (configProperties [_cfgCompatibleItems, "isNumber _x && {(getNumber _x) > 0}"]) apply {configName _x};
    };
};
_returnValue
```

**Comment by stafmoony** [comment]
Thanky ou very much. The Function seems to have worked pretty well.

**Comment by commy2** [comment]
Just to summarize, so I can point to this issue report when this question is raised AGAIN.

As Pabst wrote, there are two ways to define compatible items. Your initial code only recognizes one, and is therefore bugged.
When using CBA, most attachment items from the base game use the second definition instead of the first one due to Joint Rails being a part of CBA now.

To retrieve all compatible items of a weapon of a specific slot use:
```sqf
private _silencers = [_weapon, "muzzle"] call CBA_fnc_compatibleItems;
private _optics = [_weapon, "optic"] call CBA_fnc_compatibleItems;
private _pointers = [_weapon, "pointer"] call CBA_fnc_compatibleItems;
private _bipods = [_weapon, "bipod"] call CBA_fnc_compatibleItems;
```
This will always work correctly and report all actually compatible items.

There also is a BIS function that does this. It uses magic numbers for some reason instead:
```sqf
private _silencers = [_weapon, 101] call BIS_fnc_compatibleItems;
private _optics = [_weapon, 201] call BIS_fnc_compatibleItems;
private _pointers = [_weapon, 301] call BIS_fnc_compatibleItems;
private _bipods = [_weapon, 302] call BIS_fnc_compatibleItems;
```
The BIS function is useful when i.e. your mission is supposed to work without any mods as well. When using CBA, the BIS function is patched to recognize both possible definitions as explained above. However, if CBA is not used, the BIS function will use the actual script written by BI and not the patched version, which also recognizes only one definition of attachments, and therefore may not report all compatible items of addon weapons.
The script written by Pabst works always, but doesn't use any caching, and therefore is very slow when used multiple times for the same weapon compared to `CBA_fnc_compatibleItems`, or the patched version of `BIS_fnc_compatibleItems` when using CBA.
